### ISSUE TITLE
I need a guide

### ISSUE THREAD

**Issue by Marin-MK** [Ancurio/mkxp#166] opened 2017-06-18 09:56 UTC
So, we're making an RPG Maker XP game and would like to use this. The thing is, we have quite a few Win32API calls. When I was trying to get rid of some, I got an error which looks as follows:
https://gyazo.com/59fa82b0426d70506eeb294c76b6b443
I don't really know what I'm supposed to work with this, to be honest. I'm not very techy but interested in this nonetheless. I'm using the prebuilt Windows binary.
Also, is this project still being worked on?

**Comment by khkramer** [comment] 2017-06-18 13:28
I see you're using Pokemon Essentials.
Also I recognized your name from the PokeCommunity forums :P

This error is caused by one of essentials' custom scripts, `AudioUtilities` in specific.
In Ruby 1.8 a `:` after when was allowed, since Ruby 1.9 however it's not.
So I fixed it by simply removing the invalid characters thus making it look like:

```
def toneUS(toneType,duration,volume=95)
  case toneType
    when 0 # dialtone
      Audio.doubleSine(duration,350,440,volume)
    when 1 # busy
      Audio.doubleSine(duration,
                       SoundEnvelope.blink(480,500,500,duration),
                       SoundEnvelope.blink(620,500,500,duration),
                       volume,volume)
    when 2 # ringback
      Audio.doubleSine(duration,
                       SoundEnvelope.blink(480,2000,4000,duration),
                       SoundEnvelope.blink(440,2000,4000,duration),
                       volume,volume)
    when 3 # callfailed
      Audio.doubleSine(duration,
                       SoundEnvelope.blink(480,300,200,duration),
                       SoundEnvelope.blink(620,300,200,duration),
                       volume,volume)
  end
end
```

**Comment by Ancurio** [comment] 2017-06-18 13:34
There's currently a PR pending that would allow building mkxp with MRI 1.8, which would work around a lot of these syntax incompatibilities (at the cost of reduced performance).

The current Windows binaries are ancient btw., I'll see if I can find the time to update them.

> Also, is this project still being worked on?

I try to fix obvious and simple bugs when they're pointed out, but otherwise I currently lack the free time to make any significant progress on the larger bugs / features.

**Comment by Ancurio** [comment] 2020-08-11 13:11
Closing this as [mkxp-z](https://roza-gb.gitbook.io/mkxp-z/) should hopefully cover most needs of the Pokemn fangame community.

**Closed by Ancurio** 2020-08-11 13:11 UTC
