### ISSUE TITLE
Bitmap::DrawText seems to parse every char 10x

### ISSUE THREAD

**Issue by Keyaku** [Ancurio/mkxp#116] opened 2015-06-30 15:26 UTC
I'm not sure what's going on, but in an attempt to fix an issue with the text not being wholly presented on screen, I decided to write the following under Bitmap::DrawText:
`Debug() << "Text:" << str[0];`
I did so right after `str = fixed.c_str();`. Apparently, this function is called ten times before the first character of `str`, and it even appears to do so for every character of the original string.  
The text example is just "Test". Here's what it's logging: http://i.imgur.com/fLjb2SU.png

**Comment by Keyaku** [comment] 2015-06-30 17:14
Problem was something internal. Sorry about this.

**Comment by Keyaku** [comment] 2015-06-30 17:26
Sorry for the Close/Re-open; for a moment, thought it was a Script issue, but the Script directly calls for drawText only once and it still gets parsed 10 times.

**Comment by cremno** [comment] 2015-06-30 18:28
I can't reproduce it. Are you sure it isn't some effect (shadow, outline, or something else) implemented by some script or are you using the default ones (and then XP, VX, or VXA)?

**Comment by Ancurio** [comment] 2015-06-30 18:33
Please post a minimal test case exhibiting this behavior.

**Comment by Keyaku** [comment] 2015-07-02 14:27
Sorry for the wait.
Somehow, after I edited something that I can't recall what in mkxp, I can't seem to reproduce it anymore.  
I won't close this issue just yet as I might find out how to do it again; if I won't for a while, then you may (or I will) close this issue indefinitely.

**Comment by Ancurio** [comment] 2015-07-02 18:54
Don't worry, closing isn't a "final" thing. I'll close it for now, and if it appears again feel free to reopen this issue.

**Closed by Ancurio** 2015-07-02 18:54 UTC
