### ISSUE TITLE
Autotiles that extend past their squares don't work right (RMVX)

### ISSUE THREAD

**Issue by sorlok** [Ancurio/mkxp#107] opened 2015-05-31 00:40 UTC
Hello!

First of all, I've had great luck using MKXP, and just wanted to say "thanks"!

But I've also found an issue with auto-tiles that extend past their boundaries (this is used in RPG Maker VX for the counters and tables). In VX, they look like this:
http://i.imgur.com/Xim77Rl.png

In MKXP, they look like this:
http://i.imgur.com/cH4PzFW.png

In other words, the legs are cut off. 

Any idea what's causing this? Or what a solution might look like?

**Comment by Ancurio** [comment] 2015-05-31 03:12
Hello, since I don't own VX I can't create a test case for this, would you mind sending me your minimal project showing the bug?

**Comment by cremno** [comment] 2015-05-31 03:49
It should also be reproducible with VX Ace. The difference is that with Ace you can set the counter flag manually.

**Comment by Ancurio** [comment] 2015-05-31 04:06
@cremno I can't reproduce it with VXA.

**Comment by sorlok** [comment] 2015-05-31 04:59
Here you go. Checked it on the latest git as well as the pre-compiled binaries (and on several different machines, to rule out GPU issues).
https://drive.google.com/file/d/0B1P7NepPcOslbWhEd2E0dWl1Tnc

**Comment by sorlok** [comment] 2015-05-31 05:19
@Ancurio Interesting! You're right; the problem is not there in VX Ace. I guess these tiles just aren't being flagged correctly as "counter" types in VX? 

@cremno Are the counters determined by their position in the tileset in VX?

**Comment by Ancurio** [comment] 2015-05-31 06:54
@sorlok No, mkxp should correctly detect them as counter tiles (called "table tiles" internally), and yes, in VX, they're solely determined based upon the tile id (ie. position in the tileset).

I made an identical table in VX Ace and mkxp generated the exact same vertices for both tables, so the problem must be somewhere else..

**Comment by cremno** [comment] 2015-05-31 08:32
@Ancurio: But the tile IDs are different. For Ace that kind of table autotile causes `onTileA1()` to be called (which doesn't even care about `isTable`, so I kinda doubt mkxp draws it correctly) and for VX it's `onTileA2()`.

The following diff fixes only this specific case:
~~~diff
diff --git a/src/tileatlasvx.cpp b/src/tileatlasvx.cpp
index 8726335..5722a0c 100644
--- a/src/tileatlasvx.cpp
+++ b/src/tileatlasvx.cpp
@@ -472,9 +472,9 @@ onTileA2(Reader &reader, int16_t tileID,
         * to the screen. But in 99% of cases it shouldn't matter */
 
        if (isTable)
-               readAutotileA2(reader, patternID, orig, x, y);
-       else
                readAutotileA(reader, patternID, orig, x, y);
+       else
+               readAutotileA2(reader, patternID, orig, x, y);
 }
 
 static void
~~~

**Comment by Ancurio** [comment] 2015-05-31 09:12
@cremno Hmm, can you tell me how the tile IDs differ? I'm not sure I'm following because for the same table, I get `C7B` (left), `C71` (middle) and `C7D` (right) in both VX and VXA. Also I don't fully understand your diff, you're reading a normal autotile pattern when `onTable` is true, but table autotile pattern when it's false?

**Comment by cremno** [comment] 2015-05-31 09:13
@Ancurio : Sorry. Deleted my post because I was wrong. The actual issue is that the table is on VX layer 1 but in Ace on layer 2.

**Comment by Ancurio** [comment] 2015-05-31 09:33
@cremno Ah yes that makes a lot of sense, I was suspecting something like that but haven't dug further into it (the protruding table legs are hidden under the grass tiles).

So that means that we have parts of a lower layer that somehow need to be placed above a higher layer..

**Comment by sorlok** [comment] 2015-05-31 14:50
Possibly stupid idea, but why not just detect and raise table tiles to the A2 layer automatically? 

E.g., in onTileA1(), something like this at the end:
```
if (/* tileID == special_autotile_id */) {
	readAutotileA_But_Put_Into_A2_Layer(reader, patternID, orig, x, y);
} else {
	readAutotileA(reader, patternID, orig, x, y);
}
```

**Comment by Ancurio** [comment] 2015-05-31 15:36
@cremno Ohh I see, I misunderstood then, the table and ground tiles are on the same layer in VX so since the ground tile is parsed later and its quad is drawn over the table leg quads. Well not quite as terrible (for some reason I thought the table was below the ground layer wise).

The solution might be as simple as as parsing tiles from bottom to top instead (ie. reversing the `y` for loop).

**Comment by sorlok** [comment] 2015-05-31 15:42
@Ancurio,@cremno Parsing bottom to top seems to fix this issue. That is, changing this line in readLayer()
```
//from:
for (int y = 0; y < h; ++y)

//to:
for (int y = h-1; y >= 0 ; --y)
```

I'll do a run through the game I'm working on to see if this has any unforseen side effects, but it certainly fixes the immediate problem.

**Comment by sorlok** [comment] 2015-05-31 18:08
Playing for about an hour, nothing seems broken, and the table legs are definitely fixed.

**Comment by Ancurio** [comment] 2015-05-31 18:13
Yeah I was worried a bit that with tables extending vertically there might be quads shining through which would have previously been hidden beneath, but I couldn't find any irregularities. I will close this issue when I push the change.

**Comment by sorlok** [comment] 2015-05-31 18:24
Great, thanks for the fix!

**Closed** 2015-05-31 18:59 UTC
Labels: RGSS accuracy
